<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Animo.Monitor</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>Animo.Monitor</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scripts\Animo.csproj" />
  </ItemGroup>
</Project>
